apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-workload-registrar
  namespace: spire
data:
  k8s-workload-registrar.conf: |
    log_level = "trace"
    cert_path = "/run/spire/k8s-workload-registrar/certs/server-cert.pem"
    key_path = "/run/spire/k8s-workload-registrar/secret/server-key.pem"
    cacert_path = "/run/spire/k8s-workload-registrar/certs/cacert.pem"
    trust_domain = "ctl.org"
    cluster = "{CLUSTER_NAME}"
    server_socket_path = "/run/spire/sockets/registration.sock"
    insecure_skip_client_verification = true
    pod_label = "app"
